# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Project-Python\SailWordCard\mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_4.addWidget(self.listWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 23))
        self.menubar.setObjectName("menubar")
        self.A_file = QtWidgets.QMenu(self.menubar)
        self.A_file.setObjectName("A_file")
        self.A_help = QtWidgets.QMenu(self.menubar)
        self.A_help.setObjectName("A_help")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.fontComboBox = QtWidgets.QFontComboBox(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout.addWidget(self.fontComboBox, 0, 1, 1, 1)
        self.lineEdit_row = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_row.sizePolicy().hasHeightForWidth())
        self.lineEdit_row.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_row.setFont(font)
        self.lineEdit_row.setMaxLength(2)
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.gridLayout.addWidget(self.lineEdit_row, 3, 1, 1, 1)
        self.lineEdit_size = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_size.sizePolicy().hasHeightForWidth())
        self.lineEdit_size.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_size.setFont(font)
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.gridLayout.addWidget(self.lineEdit_size, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_col = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_col.sizePolicy().hasHeightForWidth())
        self.lineEdit_col.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_col.setFont(font)
        self.lineEdit_col.setMaxLength(2)
        self.lineEdit_col.setObjectName("lineEdit_col")
        self.gridLayout.addWidget(self.lineEdit_col, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.dockWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox.setFont(font)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 7, 1, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.dockWidget_7 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_7.setObjectName("dockWidget_7")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_num = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_num.setObjectName("label_num")
        self.gridLayout_3.addWidget(self.label_num, 0, 1, 1, 1)
        self.label_paper = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_paper.setObjectName("label_paper")
        self.gridLayout_3.addWidget(self.label_paper, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_error_num = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_error_num.setObjectName("label_error_num")
        self.gridLayout_3.addWidget(self.label_error_num, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(261, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.dockWidget_7.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_7)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_4.sizePolicy().hasHeightForWidth())
        self.dockWidget_4.setSizePolicy(sizePolicy)
        self.dockWidget_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_A = QtWidgets.QLineEdit(self.dockWidgetContents_4)
        self.lineEdit_A.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(32)
        self.lineEdit_A.setFont(font)
        self.lineEdit_A.setObjectName("lineEdit_A")
        self.horizontalLayout_2.addWidget(self.lineEdit_A)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.dockWidget_5 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_5.setObjectName("dockWidget_5")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_B = QtWidgets.QLineEdit(self.dockWidgetContents_5)
        self.lineEdit_B.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(32)
        self.lineEdit_B.setFont(font)
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.horizontalLayout.addWidget(self.lineEdit_B)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_5)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_preview = QtWidgets.QPushButton(self.dockWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preview.sizePolicy().hasHeightForWidth())
        self.pushButton_preview.setSizePolicy(sizePolicy)
        self.pushButton_preview.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.gridLayout_2.addWidget(self.pushButton_preview, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_print = QtWidgets.QPushButton(self.dockWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_print.sizePolicy().hasHeightForWidth())
        self.pushButton_print.setSizePolicy(sizePolicy)
        self.pushButton_print.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_print.setObjectName("pushButton_print")
        self.gridLayout_2.addWidget(self.pushButton_print, 1, 1, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.dockWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_del.sizePolicy().hasHeightForWidth())
        self.pushButton_del.setSizePolicy(sizePolicy)
        self.pushButton_del.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_del.setObjectName("pushButton_del")
        self.gridLayout_2.addWidget(self.pushButton_del, 0, 0, 1, 1)
        self.dockWidget_6.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_6)
        self.A_open = QtWidgets.QAction(MainWindow)
        self.A_open.setObjectName("A_open")
        self.A_save = QtWidgets.QAction(MainWindow)
        self.A_save.setObjectName("A_save")
        self.A_saveAs = QtWidgets.QAction(MainWindow)
        self.A_saveAs.setObjectName("A_saveAs")
        self.A_quit = QtWidgets.QAction(MainWindow)
        self.A_quit.setObjectName("A_quit")
        self.A_new = QtWidgets.QAction(MainWindow)
        self.A_new.setObjectName("A_new")
        self.A_about = QtWidgets.QAction(MainWindow)
        self.A_about.setObjectName("A_about")
        self.A_swc_help = QtWidgets.QAction(MainWindow)
        self.A_swc_help.setObjectName("A_swc_help")
        self.A_aboutQT = QtWidgets.QAction(MainWindow)
        self.A_aboutQT.setObjectName("A_aboutQT")
        self.A_del = QtWidgets.QAction(MainWindow)
        self.A_del.setObjectName("A_del")
        self.A_preview = QtWidgets.QAction(MainWindow)
        self.A_preview.setObjectName("A_preview")
        self.A_print = QtWidgets.QAction(MainWindow)
        self.A_print.setObjectName("A_print")
        self.A_file.addAction(self.A_new)
        self.A_file.addAction(self.A_open)
        self.A_file.addAction(self.A_save)
        self.A_file.addAction(self.A_saveAs)
        self.A_file.addSeparator()
        self.A_file.addAction(self.A_quit)
        self.A_help.addAction(self.A_about)
        self.A_help.addAction(self.A_aboutQT)
        self.menu.addAction(self.A_del)
        self.menu.addSeparator()
        self.menu.addAction(self.A_preview)
        self.menu.addAction(self.A_print)
        self.menubar.addAction(self.A_file.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.A_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sail Word Card"))
        self.A_file.setTitle(_translate("MainWindow", "文件(&F)"))
        self.A_help.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menu.setTitle(_translate("MainWindow", "操作(&E)"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "设置"))
        self.label.setText(_translate("MainWindow", "份数："))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "列数："))
        self.lineEdit_row.setText(_translate("MainWindow", "6"))
        self.lineEdit_size.setText(_translate("MainWindow", "18"))
        self.label_4.setText(_translate("MainWindow", "字号："))
        self.lineEdit_col.setText(_translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "行数："))
        self.label_3.setText(_translate("MainWindow", "字体："))
        self.checkBox.setText(_translate("MainWindow", "手动翻面"))
        self.dockWidget_7.setWindowTitle(_translate("MainWindow", "信息"))
        self.label_8.setText(_translate("MainWindow", "未配对数："))
        self.label_num.setText(_translate("MainWindow", "null"))
        self.label_paper.setText(_translate("MainWindow", "null"))
        self.label_10.setText(_translate("MainWindow", "纸张："))
        self.label_error_num.setText(_translate("MainWindow", "null"))
        self.label_6.setText(_translate("MainWindow", "词条数）："))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "A面"))
        self.dockWidget_5.setWindowTitle(_translate("MainWindow", "B面"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "操作"))
        self.pushButton_preview.setText(_translate("MainWindow", "打印预览(&V)"))
        self.pushButton.setText(_translate("MainWindow", "保存词条(&A)"))
        self.pushButton_print.setText(_translate("MainWindow", "打印(&P)"))
        self.pushButton_del.setText(_translate("MainWindow", "删除词条(&D)"))
        self.A_open.setText(_translate("MainWindow", "打开(&O)"))
        self.A_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.A_save.setText(_translate("MainWindow", "保存(&S)"))
        self.A_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.A_saveAs.setText(_translate("MainWindow", "另存为(&A)..."))
        self.A_saveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.A_quit.setText(_translate("MainWindow", "退出(&Q)"))
        self.A_new.setText(_translate("MainWindow", "新建(&N)"))
        self.A_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.A_about.setText(_translate("MainWindow", "关于 Sail Word Card(&A)"))
        self.A_swc_help.setText(_translate("MainWindow", "软件帮助(&H)"))
        self.A_swc_help.setShortcut(_translate("MainWindow", "F1"))
        self.A_aboutQT.setText(_translate("MainWindow", "关于 QT"))
        self.A_del.setText(_translate("MainWindow", "删除(&D)"))
        self.A_del.setShortcut(_translate("MainWindow", "Del"))
        self.A_preview.setText(_translate("MainWindow", "打印预览(&V)"))
        self.A_print.setText(_translate("MainWindow", "打印(&P)"))
        self.A_print.setShortcut(_translate("MainWindow", "Ctrl+P"))
